; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

	TITLE	V:\persistent\C++\HelloWorld\HelloWorld\Main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
